global N mean_arrive mean_service queue_limit device_amount t runsFileName factorPlanFileName nFeatures regressionPlanFileName;
N = 1000;
mean_arrive = 20;
mean_service = 60;
queue_limit = 25;
device_amount = 4;
t = 1.96;
runsFileName = 'pre_model.xlsx';
factorPlanFileName = 'factorPlan.xlsx';
regressionPlanFileName = 'regression.xlsx';
nFeatures = 7;